services:
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_FRONT_URL: ${VITE_FRONT_URL}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    networks:
      - matcha_network
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_FRONT_URL: ${VITE_FRONT_URL}
      VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    ports:
      - "5173:5173"
  back:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    networks:
      - matcha_network
    environment:
      IP_DATA_API_KEY: ${IP_DATA_API_KEY}
      HOST: ${HOST}
      FRONT_HOST: ${FRONT_HOST}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    ports:
      - "3000:3000"
networks:
  matcha_network:
    name: matcha_network
    driver: bridge